/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_restrpc_client_NativeRpcClient */

#ifndef _Included_org_restrpc_client_NativeRpcClient
#define _Included_org_restrpc_client_NativeRpcClient

extern JavaVM *jvm;

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_restrpc_client_NativeRpcClient
 * Method:    nativeNewRpcClient
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_restrpc_client_NativeRpcClient_nativeNewRpcClient
  (JNIEnv *, jobject);

/*
 * Class:     org_restrpc_client_NativeRpcClient
 * Method:    nativeConnect
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_restrpc_client_NativeRpcClient_nativeConnect
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_restrpc_client_NativeRpcClient
 * Method:    nativeInvoke
 * Signature: (J[B)J
 */
JNIEXPORT jlong JNICALL Java_org_restrpc_client_NativeRpcClient_nativeInvoke
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     org_restrpc_client_NativeRpcClient
 * Method:    nativeDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_restrpc_client_NativeRpcClient_nativeDestroy
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
