/* DO NOT EDIT THIS FILE - it is machine generated */

#include "org_restrpc_client_NativeRpcClient.h"
#include <rest_rpc.hpp>

#include <jni.h>

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_restrpc_client_NativeRpcClient
 * Method:    nativeNewRpcClient
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_restrpc_client_NativeRpcClient_nativeNewRpcClient
        (JNIEnv *, jobject) {
    return 10009;
}

/*
 * Class:     org_restrpc_client_NativeRpcClient
 * Method:    nativeConnect
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_restrpc_client_NativeRpcClient_nativeConnect
(JNIEnv *, jobject, jlong, jstring) {
}

/*
 * Class:     org_restrpc_client_NativeRpcClient
 * Method:    nativeInvoke
 * Signature: (J[[B)J
 */
JNIEXPORT jlong JNICALL Java_org_restrpc_client_NativeRpcClient_nativeInvoke
        (JNIEnv *, jobject, jlong, jobjectArray) {
    return 20009;
}

/*
 * Class:     org_restrpc_client_NativeRpcClient
 * Method:    nativeDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_restrpc_client_NativeRpcClient_nativeDestroy
(JNIEnv *, jobject, jlong) {

}

#ifdef __cplusplus
}
#endif
